# Generated by Django 4.2.14 on 2024-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('code', models.CharField(max_length=6, verbose_name='Verify code')),
            ],
            options={
                'verbose_name': 'Confirm Email',
                'verbose_name_plural': 'Confirm Emails',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
