# Generated by Django 4.2.14 on 2024-07-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_verifyemail_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
